#!/bin/bash

set -euo pipefail

usage() {
    echo "Usage: $0 -n my_proj [-f proj.c] [-s src] [-l MIT] [-r]" >&2
    echo "  -n Project Name (required)" >&2
    echo "  -f Filename" >&2
    echo "  -s Source Directory: proj_name/src" >&2
    echo "  -l Project License (default: MIT)" >&2
    echo "  -r Create README.md (default: false)" >&2
    exit 1
}

# Default args
name=""
src="src"
file=""
license="MIT"
readme=true

while getopts ":n:s:f:l:h" opt; do
    case $opt in
        n) name="$OPTARG" ;;
        s) src="$OPTARG" ;;
        f) file="$OPTARG" ;;
        l) license="$OPTARG" ;;
        h) usage ;;
        :) echo "Option -$OPTARG requires an argument" >&2; usage ;;
        \?) echo "Unknown option: -$OPTARG" >&2; usage ;;
    esac
done

shift $((OPTIND - 1))

if [[ -z "$name" ]]; then
    echo "Error: -n project name required" >&2
    usage
fi

if [[ $# -gt 0 ]]; then
    echo "Error: unexpected positional args" >&2
    usage
fi

mkdir -p "$name"
touch "$name/.gitignore"

if [[ -n "$src" ]]; then
    mkdir -p "$name/$src"
fi

if [[ -n "$file" ]]; then
    if [[ -n "$src" ]]; then
        touch "$name/$src/$file"
    else
        touch "$name/$file"
    fi
fi

if [[ "$readme" == true ]]; then
    cat > "$name/README.md" <<EOF
# $name

Project generated by mkproj.sh.
EOF
fi

case "$license" in
    MIT)
        cat > "$name/LICENSE" <<EOF
MIT License

Copyright (c) 2026 c3r35

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
        ;;
    *)
        echo "Error: unsupported license '$license'" >&2
        exit 1
        ;;
esac

echo "Created project: $name"


